site_name: Geneseq Documentation
site_url: http://brain.gersteinlab.org
repo_url: https://github.com/miclaraia/geneseq
site_author: Michael Laraia <micheal.laraia@gmail.com>
pages:
    - Home: index.md
    - Using Docker: docker.md
    - Application: python.md
    - Api:
        - Bodymap: api/source/app/html/js/dev/expression_bodymap.md
        - Mouse: api/source/app/html/js/dev/expression_mouse.md
        - Brainspan: api/source/app/html/js/dev/expression_brainspan.md
        - 'Spline Worker': api/source/app/html/js/dev/fit_worker.md
        - 'Data Table': api/source/app/html/js/dev/data_table.md

theme: readthedocs
