translate:
    cellType: celltype
    expr: expression
    expr_next: expression_next

table_columns:
    -
        - Gene Name
        - geneName
    -
        - Cell Type
        - cellType
    -
        - Gene Types
        - geneType
    -
        - Expression
        - expr
    -
        - Enrichment
        - expr_next

SELECT:
    gene:
        - id
        - celltype
        - expression
        - expression_next
        - geneName
        - geneID
        - geneID_human
        - geneID_mouse
        - geneType
    table:
        - id
        - celltype
        - geneType
        - expression
        - expression_next
        - geneName
    table_ajax:
        - geneName
        - cellType
        - geneType
        - expr
        - expr_next
table_sliders:
    -
        name: Expression
        column: expr
        scale: logarithmic
        min: 0
        max: 70000
        step: 10
        init:
            - 0
            - 70000
    -
        name: Fold Enrichment
        column: expr_next
        scale: logarithmic
        min: 0
        max: 5000
        step: 10
        init:
            - 0
            - 5000
    -
        name: Result Limit
        column: limit
        scale: linear
        min: 0
        max: 200
        step: 10
        init: 100