translate:
    cellType: celltype
    expr: expression
    expr_next: expression_next

readable:
    gene_chr: Chromosome

table_columns:
    -
        - Gene Mouse ID
        - _id
    -
        - Gene Human ID
        - human_id
    -
        - Cell Type
        - cell
    -
        - Expression
        - expression
    -  
        - Enrichment
        - enrichment

SELECT:
    gene:
        - id
        - celltype
        - expression
        - expression_next
        - geneName
        - geneID
        - geneID_human
        - geneID_mouse
        - geneType
    table:
        - id
        - celltype
        - geneType
        - expression
        - expression_next
        - geneName
    table_ajax:
        - geneName
        - cellType
        - geneType
        - expr
        - expr_next
table_input:
    -
        name: Expression
        column: expression
        type: slider
        scale: logarithmic
        min: 0
        max: 70000
        step: 10
        init:
            - 0
            - 70000
    -
        name: Fold Enrichment
        column: enrichment
        type: slider
        scale: logarithmic
        min: 0
        max: 5000
        step: 10
        init:
            - 0
            - 5000
    -
        name: Result Limit
        column: limit
        type: slider
        scale: linear
        min: 0
        max: 200
        step: 10
        init: 100
    -
        name: Cell Type
        column: type
        type: selection
        options:
            - astrocyte
            - striatalNeuron
            - oligodendrocyte
            - microglia

order:
    mouse:
        - _id
        - human_id
        - type
        - expression
        - enrichment